version: '3'

services:
  app:
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /Users/elizioantonioderezende/Downloads/crucial-gasket-273416-05f16ff52271.json
    volumes:
      - ${GCP_KEY_PATH}:/root/keys/keyfile.json:ro


  curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
  chmod u+x ./kustomize
